local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: false
  rolling_window: true
  width: 1.45
  height: 1.45
  resolution: 0.05 #increase to for higher res 0.025
  cost_scaling_factor: 15
  transform_tolerance: 0.5
 